# Para desarrollo local (localhost, root, sin contraseña)
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

<<<<<<< HEAD
  # Podemos desactivar Hibernate DDL auto y forzar que Spring use nuestro script SQL
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: never  # o always si quieres que cargue schema.sql en cada arranque
      schema-locations: classpath:schema.sql

=======

#Podemos desactivar Hibernate DDL auto y forzar que Spring nuestro script SQL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always # o ALWAYS si quieres que cargue schema.sql en cada arranque

app:
  security:
    cors:
      dev: true  # Deshabilita CORS para Postman en desarrollo local
>>>>>>> rodri-fullstack-main
