# Configuración base y activación de perfil

spring:
<<<<<<< HEAD
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true  # Cambia a 'dev' si quieres activar otro entorno
=======
  application:
    name: nanai_kit
  profiles:
    active: local   # Cambia a 'dev' si quieres activar otro entorno
>>>>>>> rodri-fullstack-main
